# Generated by Django 5.1.4 on 2025-01-18 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlistentry',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchlistentry',
            name='watchlist',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
        migrations.DeleteModel(
            name='WatchListEntry',
        ),
    ]
